### ISSUE TITLE
MagicMirror turns black

### ISSUE THREAD

**Issue by OberfragGER** [lavolp3/MMM-Celebrations#2]
Hi,

a soon as i add this code to my config.js... the Mirror does not start/ turn black.
Tried it twice. No chance with git pull.

`		{
		module: 'MMM-Celebrations',
		position: 'top_left',	// This can be any of the regions. Best results in left or right regions.
		header: 'Heute ist:', // This is optional
		config: {
			// You don't need any configuration options currently
			}
		},`

**Comment by lavolp3** [comment]
Above config entry works for me. Is it possible you have inserted it in the wrong section, maybe by accident into another module object?
You can check if something's wrong with the config by executing
```
npm run config:check
```
in the MagicMirror folder

**Comment by OberfragGER** [comment]
> Above config entry works for me. Is it possible you have inserted it in the wrong section, maybe by accident into another module object?
> You can check if something's wrong with the config by executing
> 
> ```
> npm run config:check
> ```
> 
> in the MagicMirror folder

iI didnt run npm install before.
Still not working!

But now i ran this command in modules folder:

`pi@MagicMirror:~/MagicMirror/modules $ npm run config:check

> magicmirror@2.14.0 config:check
> node js/check_config.js

[26.03.2021 10:48.06.808] [INFO]  Checking file...  /home/pi/MagicMirror/config/config.js
[26.03.2021 10:48.06.949] [INFO]  Your configuration file doesn't contain syntax errors :)
pi@MagicMirror:~/MagicMirror/modules $
`
The MagicMirror stays black.

**Comment by lavolp3** [comment]
Have you tried what sdetweil suggested in the forum?
```
pm2 logs --lines 100
```
Look for errors, especially ones hinting to this module.

**Comment by lavolp3** [comment]
> iI didnt run npm install before.

You must not run `npm install`
Only if it is instructed.
Running `npm install` in a module that does not contain a package.json has in the past crashed the whole mirror. There's something on that in the forum.
But let's see your pm2 log first

**Comment by OberfragGER** [comment]
I didnt run npm install before and get into that errors.

I looked into pm2 error logs an found this

`[26.03.2021 00:19.16.366] [ERROR] App threw an error during load
[26.03.2021 00:19.16.374] [ERROR] Error: Cannot find module 'cheerio'
Require stack:
- /home/pi/MagicMirror/modules/MMM-Celebrations/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:798:15)
    at Function../lib/common/reset-search-paths.ts.Module._resolveFilename (electron/js2c/browser_init.js:7718:16)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/module-alias/index.js:49:29)
    at Module._load (internal/modules/cjs/loader.js:691:27)
    at Function.Module._load (electron/js2c/asar.js:748:26)
    at Module.require (internal/modules/cjs/loader.js:853:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Celebrations/node_helper.js:12:17)
    at Module._compile (internal/modules/cjs/loader.js:968:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:986:10)
[26.03.2021 00:19.16.376] [ERROR] Whoops! There was an uncaught exception...
[26.03.2021 00:19.16.381] [ERROR] Error: Cannot find module 'cheerio'
Require stack:
- /home/pi/MagicMirror/modules/MMM-Celebrations/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:798:15)
    at Function../lib/common/reset-search-paths.ts.Module._resolveFilename (electron/js2c/browser_init.js:7718:16)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/module-alias/index.js:49:29)
    at Module._load (internal/modules/cjs/loader.js:691:27)
    at Function.Module._load (electron/js2c/asar.js:748:26)
    at Module.require (internal/modules/cjs/loader.js:853:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Celebrations/node_helper.js:12:17)
    at Module._compile (internal/modules/cjs/loader.js:968:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:986:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/pi/MagicMirror/modules/MMM-Celebrations/node_helper.js',
    '/home/pi/MagicMirror/js/app.js',
    '/home/pi/MagicMirror/js/electron.js',
    '/home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js',
    undefined
  ]
}
[26.03.2021 00:19.16.383] [ERROR] MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
[26.03.2021 00:19.16.383] [ERROR] If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
[26.03.2021 00:19.16.668] [WARN]  (electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
[26.03.2021 00:21.20.547] [WARN]  (electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
[26.03.2021 00:21.35.668] [ERROR] (node:3049) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
[26.03.2021 06:59.57.990] [WARN]  (electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
[26.03.2021 07:08.08.191] [ERROR] (node:907) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
[26.03.2021 07:45.25.600] [WARN]  (electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
[26.03.2021 08:52.27.590] [WARN]  (electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
[26.03.2021 08:52.33.190] [ERROR] (node:1084) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
[1084:0326/085951.304862:FATAL:gpu_data_manager_impl_private.cc(1034)] The display compositor is frequently crashing. Goodbye.
[26.03.2021 10:07.05.840] [WARN]  (electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
[26.03.2021 10:19.45.577] [ERROR] (node:1028) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
[26.03.2021 10:46.44.228] [WARN]  (electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
[26.03.2021 10:48.14.294] [ERROR] (node:6246) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
[26.03.2021 10:50.05.897] [WARN]  (electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
[26.03.2021 10:50.16.635] [ERROR] (node:6642) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated`

**Comment by lavolp3** [comment]
Ok my mistake you actually need to do `npm install` 
The module helper is looking for cheerio. 
So please try to do that and try again

**Comment by OberfragGER** [comment]
> Ok my mistake you actually need to do `npm install`
> The module helper is looking for cheerio.
> So please try to do that and try again

No worries. Somehow my installation ist now broken. Dont have any clue. Something is eating my RAM. So i will install an 1 month old image. I will try celebrations at first and give you some feedback. Just for info- npm install is missing in the instructions.

**Comment by lavolp3** [comment]
Yeah just included it.

**Comment by lavolp3** [comment]
I will close this for now since you are planning to use an older install and the issue cannot be solved anymore. Let me know if you still experience problems after new installation.

**Comment by OberfragGER** [comment]
Youre right. Its working now.

**Comment by OberfragGER** [comment]
Just for info:
During installation:
`pi@MagicMirror:~/MagicMirror/modules/MMM-Celebrations $ npm install

npm WARN deprecated cheerio-select-tmp@0.1.1: Use cheerio-select instead
npm notice created a lockfile as package-lock.json. You should commit this file.
added 81 packages from 27 contributors and audited 81 packages in 12.668s

13 packages are looking for funding
  run `npm fund` for details

found 1 high severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
pi@MagicMirror:~/MagicMirror/modules/MMM-Celebrations $
pi@MagicMirror:~/MagicMirror/modules/MMM-Celebrations $ npm audit fix
up to date in 1.471s

13 packages are looking for funding
  run `npm fund` for details

fixed 0 of 1 vulnerability in 81 scanned packages
  1 package update for 1 vulnerability involved breaking changes
  (use `npm audit fix --force` to install breaking changes; or refer to `npm aud                                                                                        it` for steps to fix these manually)
`
